### ISSUE TITLE
Race condition between player manager and individual players.

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#4]
Player manager general behaviour:
* On `start(self)`:
  * Connects to dbus.
  * Spawns one player instance per level:
    * Spawns a new process.
    * Tracks/waits process start.
    * Tracks/waits process connection to dbus.
    * Instructs it to pause, via dbus.
  * Unpauses level 0 player.
* On `level(self, new_level, comment='')`:
  * It unpauses the respective level player.
* Then `_player_ended(self, level)`:
   * Tracks player termination and spawns a new player instance associated to that level.

The race condition:
* Player manager started and level 0 is playing.
* `level(new_level=X)` called: player unpaused, level X video is played, fades out and player process terminates.
* Player manager detects that via `_player_ended(level=X)`: spawns new level X player.
* `level(new_level=X)` called before just spawned level X player is ready.
* Player manager tries to unpause player X which fails because the process/dbus attachment isn't completed yet.

This would be within acceptable limits if a subsequent level X trigger would work. Unfortunately it does not, so this must be fixed.

Possible fix will need to not only track player termination but also player readiness.

Below is a `player.*` debug level log of the occurrence:
```
18:14:03.001381 [player.mngr#info] new_level=1 comment='network'
18:14:03.003097 [player.each.com.nunogodinho.vela2017-1-01#debug] asking player to play/pause
18:14:03.017497 [player.each.com.nunogodinho.vela2017-1-01#debug] asked player to play/pause
18:14:03.019412 [player.each.com.nunogodinho.vela2017-1-01#info] fade in starting
18:14:03.020830 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 0
18:14:03.058684 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 96.381676197052
18:14:03.099508 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 200.49487352371216
18:14:03.161713 [player.each.com.nunogodinho.vela2017-1-01#info] fade in completed
18:14:05.940658 [player.each.com.nunogodinho.vela2017-1-01#info] fade out starting
18:14:05.942076 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 255
18:14:05.969577 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 240.94610452651978
18:14:06.010768 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 219.9284291267395
18:14:06.040127 [player.mngr#info] new_level=1 comment='network'
18:14:06.052054 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 198.8754916191101
18:14:06.092972 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 178.01369905471802
18:14:06.133929 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 157.1235752105713
18:14:06.175132 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 136.11124992370605
18:14:06.216207 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 115.15485763549805
18:14:06.257382 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 94.16709423065186
18:14:06.298490 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 73.2254147529602
18:14:06.339461 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 52.30732440948486
18:14:06.380493 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 31.374034881591797
18:14:06.391978 [player.mngr#info] new_level=1 comment='network'
18:14:06.421738 [player.each.com.nunogodinho.vela2017-1-01#debug] alpha 10.33787727355957
18:14:06.484176 [player.each.com.nunogodinho.vela2017-1-01#info] fade out completed
18:14:06.567999 [player.dbus#debug] signal data=(':1.24', ':1.24', '')
18:14:06.574260 [player.dbus#debug] signal data=('com.nunogodinho.vela2017-1-01', ':1.23', '')
18:14:06.577890 [player.dbus#debug] signal data=(':1.23', ':1.23', '')
18:14:06.580275 [player.proc.com.nunogodinho.vela2017-1-01#debug] stdout: b'Video codec omx-h264 width 1280 height 720 profile 77 fps 25.000000\nSubtitle count: 0, state: off, index: 1, delay: 0\nV:PortSettingsChanged: 1280x720@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:1 alpha:0 aspectMode:0\nhave a nice day ;)\n'
18:14:06.585271 [player.proc.com.nunogodinho.vela2017-1-01#debug] player process ended; exit_code=0
18:14:06.587023 [player.mngr#info] player level=1 ended
18:14:06.588351 [player.mngr#info] creating player level=1
18:14:06.590380 [player.each.com.nunogodinho.vela2017-1-01#info] spawning player 'com.nunogodinho.vela2017-1-01'
18:14:06.591918 [player.dbus#info] tracking dbus player 'com.nunogodinho.vela2017-1-01'
18:14:06.593308 [player.mngr#debug] executable is '/usr/bin/omxplayer.bin'
18:14:06.595053 [player.mngr#debug] executable is '/usr/bin/omxplayer.bin'
18:14:06.603210 [player.proc.com.nunogodinho.vela2017-1-01#debug] player process started
18:14:06.607334 [player.dbus#info] waiting player 'com.nunogodinho.vela2017-1-01' start
18:14:06.712040 [player.mngr#info] new_level=1 comment='network'
18:14:06.713216 [player.each.com.nunogodinho.vela2017-1-01#debug] asking player to play/pause
18:14:06.714924 [twisted.internet.defer#critical] Unhandled error in Deferred:
18:14:06.715876 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/tiago.montes/pyVela2017.venv/lib/python3.4/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	  File "/home/tiago.montes/pyVela2017.venv/lib/python3.4/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/tiago.montes/pyVela2017/player/player.py", line 200, in play
	    yield self.play_pause()
	  File "/home/tiago.montes/pyVela2017.venv/lib/python3.4/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/home/tiago.montes/pyVela2017.venv/lib/python3.4/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/tiago.montes/pyVela2017/player/player.py", line 190, in play_pause
	    yield self._dbus_player.callRemote(
	builtins.AttributeError: 'NoneType' object has no attribute 'callRemote'
	
18:14:06.791978 [player.dbus#debug] signal data=(':1.25', '', ':1.25')
18:14:06.794413 [player.dbus#debug] signal data=('com.nunogodinho.vela2017-1-01', '', ':1.25')
18:14:06.795625 [player.dbus#info] player 'com.nunogodinho.vela2017-1-01' started
18:14:06.796671 [player.each.com.nunogodinho.vela2017-1-01#debug] getting dbus player object
18:14:06.797847 [player.each.com.nunogodinho.vela2017-1-01#debug] got dbus player object
18:14:06.801525 [player.dbus#debug] signal data=(':1.26', '', ':1.26')
18:14:06.897648 [player.each.com.nunogodinho.vela2017-1-01#info] duration is 3.52s
18:14:06.899038 [player.each.com.nunogodinho.vela2017-1-01#debug] asking player to play/pause
18:14:06.917616 [player.each.com.nunogodinho.vela2017-1-01#debug] asked player to play/pause
18:14:06.983720 [player.mngr#info] new_level=1 comment='network'
```

**Comment by tmontes** [comment]
Fixed with merge #6. Closing.
